name = "JpegGlitcher"
uuid = "7e1ea31b-b9a5-4cc0-940e-7c5f7cd080d6"
authors = ["Théo Galy-Fajou <theo.galyfajou@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JpegTurbo = "b835a17e-a41a-41e7-81f0-2f016b05efe0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
JpegTurbo = "0.1"