name = "JpegGlitcher"
uuid = "7e1ea31b-b9a5-4cc0-940e-7c5f7cd080d6"
authors = ["Théo Galy-Fajou <theo.galyfajou@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
